### ISSUE TITLE
Documentation link returns 404

### ISSUE THREAD

**Issue by hammerhead** [crate-workbench/cratedb-toolkit#142]
Hi @amotl,

I recently sent out references to cratedb-toolkit to a few users. In the README, there is a link to the documentation pointing to https://cratedb-toolkit.readthedocs.io/ which returns a 404. Is there documentation already available that can be linked to or does it still need to be created?

Thanks!

**Comment by amotl** [comment]
Thanks for your feedback. Documentation still needs to be whipped up, there is currently a void. Apologies.

**Comment by amotl** [comment]
Hi again. We spent some cycles on establishing a proper documentation. Thanks for the bump.

### Status Quo

#### Live
- [CrateDB Toolkit](https://cratedb-toolkit.readthedocs.io/)

  The "Datasets API", the "I/O Subsystem", and the "Retention and Expiration" subsystem are the most prominent ones already shipping with Toolkit, so you will already find corresponding documentation about them.

#### Preview
Both subsystems are included in GH-88, and need some more love before integrating. Let us know about your needs and interest, so we can adjust velocity correspondingly.

- [CrateDB CFR](https://cratedb-toolkit--88.org.readthedocs.build/cfr/)
- [CrateDB WTF](https://cratedb-toolkit--88.org.readthedocs.build/wtf/)


### Outlook

Please review and validate the documentation, and don't hesitate to provide any kind of feedback to improve. Thank you! 🙏

**Comment by amotl** [comment]
Closing this, because navigating to the documentation does not yield a 404 response any longer. Please re-open when applicable, or create a new issue for conveying back suggestions for improvements. Thanks!
